### ISSUE TITLE
error tryning to build external on linux 64 bit

### ISSUE THREAD

**Issue by husk00** [Ant1r/ofxPof#1]
Hi, this is the error I get when trying to build external on linux/ubuntu 64 bit machine:
/usr/bin/ld: obj/linux64/Release/src/ofApp.o: relocation R_X86_64_32 against `thread' can not be used when making a shared object; recompile with -fPIC

thanks and congrats for this work!

husk

**Comment by Ant1r** [comment]
Maybe you could try to edit buildExternal/config.make,  and to change these lines :

`ifeq ($(PLATFORM_OS),Linux)`
`APPNAME = pof.pd_linux`
`PROJECT_LDFLAGS = -fPIC -Wl,--export-dynamic -rdynamic -shared -Wl,-rpath=./libs`

to :

`ifeq ($(PLATFORM_OS),Linux)`
`APPNAME = pof.pd_linux`
`PROJECT_CFLAGS = -fPIC`
`PROJECT_LDFLAGS = -Wl,--export-dynamic -rdynamic -shared -Wl,-rpath=./libs`

(sorry, fPIC is not a linking but a compile option...)

**Comment by husk00** [comment]
Your suggestion resolved the error, but now I get this one:

/usr/bin/ld: ../../../libs/openFrameworksCompiled/lib/linux64/libopenFrameworks.a(ofAppRunner.o): relocation R_X86_64_32 against `_ZN4Poco20NullPointerExceptionD1Ev' can not be used when making a shared object; recompile with -fPIC
../../../libs/openFrameworksCompiled/lib/linux64/libopenFrameworks.a: error adding symbols: Bad value

seems some kind of error between 32 and 64 bit stuff.

thanks

**Comment by Ant1r** [comment]
Try to clean your whole ofx tree (not sure if just a "make clean" is
enough). This should re-build libopenFrameworks.a with -fPIC.

2015-03-30 20:19 GMT+02:00 husk00 notifications@github.com:

**Comment by husk00** [comment]
I downloaded again the whole addon, I modified config.make with FPIC cflag and trying to recompile the externals but same result:
/usr/bin/ld: ../../../libs/openFrameworksCompiled/lib/linux64/libopenFrameworks.a(ofAppRunner.o): relocation R_X86_64_32 against `_ZN4Poco20NullPointerExceptionD1Ev' can not be used when making a shared object; recompile with -fPIC

thanks

**Comment by Ant1r** [comment]
I didn't mean to clean the addon tree but really the ofx tree : remove  `libs/openFrameworksCompiled/lib/*` and rebuild.

**Comment by husk00** [comment]
Nothing changed.
I gave up and I installed a chrooted 32 bit system. Every thing went fine there.

**Comment by pettter** [comment]
There are still (again?) problems with compiling on 64bits.. Also generally against the bleeding-edge OFX stuff (UTF8Iterator naming conflicts, thread ambiguities).

Specifically, it seems like OF doesn't generally use libs compiled with -fPIC (libkiss, libtess2, perhaps more?), so it's not possible to compile an external from it. libkiss could be recompiled, but libtess2 source isn't even included in the distribution... This should probably at least partly be an issue upstream, I'm guessing.

**Comment by Ant1r** [comment]
Pof linux64 is now readily available through deken search engine!
 In the "release" folder you can find 64bit OF libs compiled with -fPIC if you really want to compile by yourself... I'll try to give better info about building for 64bit.
