### ISSUE TITLE
poffilm[-help] not working

### ISSUE THREAD

**Issue by neopostmodern** [Ant1r/ofxPof#4]
I tried to open the poffilm help. It first took me a bit to see that I needed to trigger the filename (`[symbol img/fingers.mov]`) for anything to happen - maybe add a comment there?

Then the pd log states:
```
tried /home/neopostmodern/.local/lib/pd/pof/img/fingers.mov and succeeded
```

Next I got this error in the terminal from which pd was launched: 
```
[ error ] ofGstUtils: startPipeline(): unable to pause pipeline
```

Nothing is shown. Toggling the checkbox above `[play $1]` nor anything else has any effect (no output in log or terminal either). Tried started both with and without the `-lib pof` parameter.

Other examples (such as the `pofimage-help`) do work though.

**Comment by Ant1r** [comment]
hmmm... I guess gstreamer can't find its plugins. Maybe they could also be added them to linux distribution (cost about 11Mb...).
Could you try installing gstreamer1.0-plugins-base/good/bad/(ugly) if not already there ?
Thanks

**Comment by neopostmodern** [comment]
I think I do have all of them?
```
$ dpkg -l | grep gstreamer1.0-plugin
ii  gstreamer1.0-plugins-bad:amd64                                   1.10.4-1ubuntu1                                           amd64        GStreamer plugins from the "bad" set
ii  gstreamer1.0-plugins-bad-faad:amd64                              1.10.4-1ubuntu1                                           amd64        GStreamer faad plugin from the "bad" set
ii  gstreamer1.0-plugins-bad-videoparsers:amd64                      1.10.4-1ubuntu1                                           amd64        GStreamer videoparsers plugin from the "bad" set
ii  gstreamer1.0-plugins-base:amd64                                  1.10.4-1ubuntu1                                           amd64        GStreamer plugins from the "base" set
ii  gstreamer1.0-plugins-base:i386                                   1.10.4-1ubuntu1                                           i386         GStreamer plugins from the "base" set
ii  gstreamer1.0-plugins-base-apps                                   1.10.4-1ubuntu1                                           amd64        GStreamer helper programs from the "base" set
ii  gstreamer1.0-plugins-good:amd64                                  1.10.4-1ubuntu1                                           amd64        GStreamer plugins from the "good" set
ii  gstreamer1.0-plugins-ugly:amd64                                  1.10.4-1ubuntu1                                           amd64        GStreamer plugins from the "ugly" set
ii  gstreamer1.0-plugins-ugly-amr:amd64                              1.10.4-1ubuntu1                                           amd64        GStreamer plugins from the "ugly" set
```
I have tried various codecs without any success.

Is there any way to figure out which plugins it's trying to load and see where that fails?

**Comment by neopostmodern** [comment]
I just figured that I should have pasted much more of the terminal output:
```
(puredata:24097): GStreamer-WARNING **: Failed to load plugin '/usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstplayback.so': /usr/lib/x86_64-linux-gnu/libgsttag-1.0.so.0: undefined symbol: gst_element_message_full_with_details

(puredata:24097): GLib-GObject-CRITICAL **: g_object_ref_sink: assertion 'G_IS_OBJECT (object)' failed

(puredata:24097): GLib-GObject-CRITICAL **: g_object_set: assertion 'G_IS_OBJECT (object)' failed

(puredata:24097): GLib-GObject-CRITICAL **: g_object_set: assertion 'G_IS_OBJECT (object)' failed

(puredata:24097): GStreamer-CRITICAL **: gst_element_get_bus: assertion 'GST_IS_ELEMENT (element)' failed

(puredata:24097): GStreamer-CRITICAL **: gst_object_unref: assertion 'object != NULL' failed

(puredata:24097): GStreamer-CRITICAL **: gst_element_set_state: assertion 'GST_IS_ELEMENT (element)' failed
[ error ] ofGstUtils: startPipeline(): unable to pause pipeline
```
That first line refers to [this](https://gstreamer.freedesktop.org/data/doc/gstreamer/head/gstreamer/html/GstElement.html#gst-element-message-full-with-details) but that should be included in the version of GStreamer I have installed...

**Comment by Ant1r** [comment]
> that should be included in the version of GStreamer

yep, but apparently not in the one that is distributed along pof (into pof/.libs)... 
As `gst_element_message_full_with_details` has only been introduced with gst1.10, it seems that pof/.libs/libgst*.xxx are older than 1.10 (I will check this later).

Maybe if you remove that ones and replace them by links to your gst libs it could work (or alternatively you could try downgrading your plugins to the version number of included gstreamer)...

But I think I'll really have to include plugins also into pof's distribution for linux.

**Comment by neopostmodern** [comment]
Great suggestion...
```
cd ~/.local/lib/pd/pof/libs
mv libgstreamer-1.0.so.0 libgstreamer-1.0.so.0.bak
ln -s /usr/lib/x86_64-linux-gnu/libgstreamer-1.0.so.0 libgstreamer-1.0.so.0
mv libgstvideo-1.0.so.0 libgstvideo-1.0.so.0.bak
ln -s /usr/lib/x86_64-linux-gnu/libgstvideo-1.0.so libgstvideo-1.0.so.0
mv libgstbase-1.0.so.0 libgstbase-1.0.so.0.bak
ln -s /usr/lib/x86_64-linux-gnu/libgstbase-1.0.so libgstbase-1.0.so.0
```
...and it works!

Feel free to close if this isn't withing the scope of ofxPof. Maybe add a comment to the README or something.

**Comment by Ant1r** [comment]
Latest pof0.1.7 from deken for Linux32/64 is now packaged with Gst(libs&plugins). It should load included gst libs which will scan only included plugins dir.
So... just backup your old one and try this if you want!
