### ISSUE TITLE
threshold-based alpha?

### ISSUE THREAD

**Issue by neopostmodern** [Ant1r/ofxPof#5]
I have seen `[pofcolor]` to manipulate the color and alpha mix for a given image. Is there a possibility to apply a certain alpha (potentially also color) based on a threshold, such as the forth and fifth parameter to `[pix_alpha]`?

**Comment by Ant1r** [comment]
This falls more within the scope of shaders... which are now supported by Pof ! And `[pofshader]`'s help patch just exposes this functionality as an example. 
Unfortunately latest deken version doesn't include this yet. I'll try updating soon.

**Comment by Ant1r** [comment]
Deken versions now include [pofshader], excepting for arm6 (rPi...) because this needs GLES2 which breaks some objects (e.g texts), but this is another issue. Closing this one.
