### ISSUE TITLE
pofxml freezes pd parsing large files

### ISSUE THREAD

**Issue by emviveros** [Ant1r/ofxPof#6]
Hello!

I tried to use pofxml to parse large xml files and it freezes pd.

The one of the files which pofxml failed are in: [map_true.xml.zip](https://forum.pdpatchrepo.info/uploads/files/1534109081004-map_true.xml.zip)

Patch example:
![patch_pofxml_test](https://user-images.githubusercontent.com/3089536/45247411-dff9b280-b2dd-11e8-801b-4f1aaea83305.png)

Thanks a lot for pof!! :)

**Comment by Ant1r** [comment]
Running Pd from a terminal allows getting some info, here:
[ error ] ofXml: parse error: Invalid token in line 24178 column 121
Your file has a missing quote at this place.
That said, even after fixing the xml file, querying "getnum nodes" hangs Pd forever for me... So I'll try building a simple test to see if ofXML alone (without Pd) succeeds or not.

**Comment by Ant1r** [comment]
Actually Pd doesn't hang forever, but takes ~5mn to  "getnum nodes" from your (corrected) file, then correctly returns:
`print: 20041`

An OF test app doing the same operation also takes a lot of time (though less than Pof version) before returning the same result 20041. This test app is basically:

```
    XML.load("map_true.xml");    
    XML.setTo("nodes");    
    int num = XML.getNumChildren();
    ofLogNotice("num nodes =")<<num<<endl;

``` 
(tested with OF 0.9.4 linux64).

More investigation would be needed to know why its takes so long, and if there is a way to do it faster. Sure, your file is rather large (more than 16Mbytes and 47045 lines), but I think it should be way faster anyway.

**Comment by emviveros** [comment]
First, thanks for verify this issue.. 

Yeah.. In linux64 I can parse the file with little patience with pd 0.49test3 (2min). In OSx it only freezes pd48-2 (+20min..). In RPi I haven' t tested it yet, but I don't think it would be better.. 

I can't see how I can help in the way of parsing method for the external. If I can parse this file with other method with success I report it here.

**Comment by Ant1r** [comment]
I recently introduced a new [pofxmlp] object, which is based on pugixml library, which was also chosen by OF for latest ofXml implementation (since OF 0.10).
I didn't test with this big XML file, but maybe it will behave better!

**Comment by emviveros** [comment]
Sorry for delay...hahahah ok.. I tested [pofxmlp] and works like a miracle! Thanks!!
