### ISSUE TITLE
Getting SEgmentation Fault on Ubuntu 22.04

### ISSUE THREAD

**Issue by jimruxton** [Ant1r/ofxPof#9]
When loading an example file after installing the external in PD I get a segmentation fault. This is what I get in the terminal below. Maybe I'm not installing correctly?

```
[ error ] ofAppGLFWWindow: 65544: GLX: Failed to create context: BadValue (integer parameter out of range for operation)
[ error ] ofAppGLFWWindow: couldn't create GLFW window
Segmentation fault (core dumped)

```

**Comment by Ant1r** [comment]
Did you install with Deken? 
Did you try to install different Pof versions?

**Comment by jimruxton** [comment]
Yes I installed from Deken. I haven't tried different versions.

**Comment by Ant1r** [comment]
Thanks. Pof (like any OF project...) is quite challenging to package for Linux, because of the external dependencies.
So your problem could be related to incompatibilities between the libraries supplied with Pof and your system (I never compiled Pof on an Ubuntu 22.04).

Here is a built from an Ubuntu 20.04, tell me if it works for you:
https://filevert.fr/d/2t_5B_s_5D_Am9X_5B_s_5D_VcT2HfukJSE=

**Comment by jimruxton** [comment]
Thanks I downloaded and tried this Deken file and am no longer getting a segmentation fault however I'm getting this error message in the console
``
 libPocoNet.so.62: cannot open shared object file: No such file or directory
``

I tried installing this library however it wasn't available for Ubuntu 22.04 . libpoconet80 was available so I installed that and tried symlinking  libPocoNet.so.62 to  libPocoNet.so.80 but still got the same error message. Not sure if this info helps you track down the issue.

**Comment by Ant1r** [comment]
Thanks for this info. I'm afk now but I'll check this a bit later in the day.

Can you tell if this library is present in pof/libs/ ?

**Comment by Ant1r** [comment]
Please try this new version, which includes the needed libPoco*:
https://filevert.fr/d/2t_5B_s_5D_FltXyVpKmGKP9IyU=

**Comment by jimruxton** [comment]
Thanks I still got a couple of errors but after installing the 2 libraries: librtaudio6 and libglfw3    everyting looks good. I haven't had a deep dive yet but so far so good. Thanks a lot for the help.

**Comment by Ant1r** [comment]
Thanks for testing and helping to debug!
I'm adding librtaudio and libglfw to the libs to ship with. I'll push a new build to Deken soon.
